-- MySQL Script generated by MySQL Workbench
-- Sun May 24 14:00:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `shoes` ;

-- -----------------------------------------------------
-- Table `shoes`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`role_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`role_id` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login` (`login` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `shoes`.`role_id` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(50) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `order_date` DATE NOT NULL,
  `delivery_date` DATE NOT NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `category_id` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `manufacture_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL DEFAULT '0',
  `discount` INT NOT NULL DEFAULT '0',
  `image` VARCHAR(255) NULL DEFAULT 'picture.png',
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `manufacture_id` (`manufacture_id` ASC) VISIBLE,
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shoes`.`categories` (`id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`manufacture_id`)
    REFERENCES `shoes`.`manufacturers` (`id`),
  CONSTRAINT `products_ibfk_3`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `shoes`.`suppliers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `shoes`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoes`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_items_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `shoes`.`orders` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `order_items_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `shoes`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


INSERT INTO role_id(name) VALUES
('admin'), ('manager'), ('client');

INSERT INTO users(full_name, login, password, role_id) VALUES
('Администратор Системы', 'admin', 'admin', 1),
('Менеджер Иванов', 'manager', 'manager', 2),
('Клиент Петров', 'client', 'client', 3);

INSERT INTO categories(name) VALUES
('Кроссовки'), ('Ботинки'), ('Туфли'), ('Сандалии');

INSERT INTO manufacturers(name) VALUES
('Nike'), ('Adidas'), ('Ralf Ringer'), ('Ecco');

INSERT INTO suppliers(name) VALUES
('ООО Поставка'), ('ИП Складов'), ('ShoeMarket');

INSERT INTO products
(name, category_id, description, manufacture_id, supplier_id, price, quantity, discount, image)
VALUES
('Nike Air Run', 1, 'Легкие беговые кроссовки', 1, 1, 7990.00, 12, 10, 'picture.png'),
('Adidas Street', 1, 'Повседневные кроссовки', 2, 2, 6490.00, 4, 20, 'picture.png'),
('Ralf Classic', 3, 'Классические мужские туфли', 3, 1, 5990.00, 8, 0, 'picture.png'),
('Ecco Winter', 2, 'Зимние ботинки', 4, 3, 11990.00, 2, 15, 'picture.png'),
('Summer Sandals', 4, 'Летние сандалии', 4, 2, 3490.00, 0, 5, 'picture.png');

INSERT INTO orders(status, address, order_date, delivery_date) VALUES
('Новый', 'г. Москва, ул. Ленина, 1', '2026-05-01', '2026-05-05'),
('Выдан', 'г. Санкт-Петербург, Невский пр., 10', '2026-05-03', '2026-05-07');

INSERT INTO order_items(order_id, product_id, count) VALUES
(1, 1, 1),
(1, 2, 2),
(2, 3, 1);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
